trigger:
    branches:
      include:        
        - master  
pool:
  vmImage: "ubuntu-latest"

variables: 
  BuildConfiguration: 'release'
  

pr: none
  
steps:

  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.1'
      includePrerelease: false
    displayName : "Configurando gitversion"

  - task: gitversion/execute@0
    inputs:
      useConfigFile: true
      configFilePath: "deploy/gitConfig.yml" 
    displayName: "generando la nueva versión"
  
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)/packages/gatsby-theme-aio/'
      customCommand: "version $(SemVer)  --no-git-tag-version"
      customRegistry: 'useFeed'
      customFeed: '0e468e6a-c444-43d7-95e1-61f36d80dbd2/95b187e5-3345-428f-b872-48ed857dec92'
      
  - task: CopyFiles@2
    inputs:
      sourceFolder: $(Build.SourcesDirectory)/packages/gatsby-theme-aio
      contents: "**"
      targetFolder: $(Build.ArtifactStagingDirectory)/npm
    displayName: "Copy Build"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)/npm"
      artifactName: npm
    displayName: "Publish npm artifact"


