trigger:
    branches:
      include:        
        - main  
pool:
  vmImage: "ubuntu-latest"

variables: 
  BuildConfiguration: 'release'
pr: none
  
steps:


  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.1'
      includePrerelease: false
    displayName : "Configurando gitversion"

  - task: gitversion/execute@0
    inputs:
      useConfigFile: true
      configFilePath: "deploy/gitConfig.yml" 
    displayName: "generando la nueva versión"
  
  - task: Npm@1
<<<<<<< HEAD
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)/packages/gatsby-theme-aio/'
      customCommand: 'version $(SemVer)  --no-git-tag-version'
      customRegistry: 'useFeed'
      customFeed: '$(default-feed)'
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: '$(Build.SourcesDirectory)/packages/gatsby-theme-aio/'
      customRegistry: 'useFeed'
      customFeed: '$(default-feed)'

=======
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)/Package'
      customCommand: '--no-git-tag-version version $(SemVer).build.$(Build.BuildId)'
      
>>>>>>> b42cc8844fb4c6be6a6f9b0bebbc9be6456fe6e6

  - task: CopyFiles@2
    inputs:
      sourceFolder: $(Build.SourcesDirectory)/packages/gatsby-theme-aio
      contents: "**"
      targetFolder: $(Build.ArtifactStagingDirectory)/npm
    displayName: "Copy Build"

  - task: Npm@1
    inputs:
      command: 'publish'
      workingDir: '$(Build.SourcesDirectory)/packages/gatsby-theme-aio'
      publishRegistry: 'useFeed'
      publishFeed: '$(default-feed)'


